name: ColaCore
main: net.cubiness.colachampionship.ColaCore
version: 1.0
api-version: 1.15
depend: [ProtocolLib]
commands:
  minigame:
    description: Set cola championship minigame
    permission: cc.minigame
    usage: /minigame (start <minigame> | stop)
  score:
    description: Alter score of player in cola championship
    permission: cc.score
    usage: /score <add | remove | set> <username> <value>
  showscore:
    description: Shows the minigame or total score for all players
    permission: cc.showscore
    usage: /showscore (total | minigame <minigame>)
  joinall:
    description: Puts all players into a minigame
    permission: cc.joinall
    usage: /joinall <minigame>
  join:
    description: Puts the players into a minigame
    permission: cc.join
    usage: /join <minigame>
  leave:
    description: Removes the player from a minigame
    permission: cc.leave
    usage: /leave
  hub:
    description: Teleports you to the hub
    permission: cc.hub
    usage: /hub
  cola:
    description: ColaCore admin commands
    permission: cc.admin
    usage: /cola [reload]
permissions:
  cc.admin:
    description: ColaCore admin commands
    default: op
  cc.minigame:
    description: Permission to run /minigame
    default: op
  cc.score:
    description: Permission to alter players' score
    default: op
  cc.showscore:
    description: Permission to show different scoreboard
    default: true
  cc.joinall:
    description: Permission to send all players minigame
    default: op
  cc.join:
    description: Permission to join a minigame
    default: true
  cc.leave:
    description: Permission to leave a minigame
    default: true
  cc.hub:
    description: Permission to teleport to hub
    default: true
