name: ColaCore
main: net.cubiness.colachampionship.ColaCore
version: 1.0
api-version: 1.15
commands:
  minigame:
    description: Set cola championship minigame
    permission: cc.minigame
    usage: /minigame (start <minigame> | stop)
  score:
    description: Alter score of player in cola championship
    permission: cc.score
    usage: /score <add | remove | set> <username> <value>
  showscore:
    description: Shows the minigame or total score for all players
    permission: cc.score
    usage: /showscore <total | minigame>
  join:
    description: Puts player into the lobby of a minigame
    permission: cc.join
    usage: /join <minigame>
  joinall:
    description: Puts all players into a minigame
    permission: cc.joinall
    usage: /joinall <minigame>
  leave:
    description: Removes the player from whatever minigame they were in, if any
    permission: cc.leave
    usage: /leave
  updatescoreboard:
    description: Fixes scoreboard
    permission: cc.updatescoreboard
    usage: /updatescoreboard
permissions:
  cc.minigame:
    description: Permission to run /minigame
    default: op
  cc.score:
    description: Permission to alter players' score
    default: op
  cc.join:
    description: Permission to join minigame
    default: true
  cc.joinall:
    description: Permission to send all players minigame
    default: op
  cc.leave:
    description: Permission to leave minigame
    default: true
  cc.updatescorebord:
    description: Permission to fix scoreboard
    default: true
