name: ColaChampionship
main: net.cubiness.colachampionship.Main
version: 1.0
api-version: 1.15
commands:
  minigame:
    description: Set cola championship minigame
    permission: cc.minigame
    usage: /minigame <minigame name>
  score:
    description: Alter score of player in cola championship
    permission: cc.score
    usage: /score <add|remove|set> <username> <value>
  showscore:
    description: Shows the minigame or total score for all players
    permission: cc.score
    usage: /showscore <total|minigame>
permissions:
  cc.minigame:
    description: Permission to run /minigame
    default: op
  cc.score:
    description: Permission to alter players' score
    default: op
